
version: '3'

services:
  app:
    build: .
    ports:
      - "9991:8000"
      

    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
